name: Ofp Decrypter by Area69Labs..

on:
#  release:
#    types: [published]
#  push:
#    branches:
#      - master
#    paths:
#      - '.config'
#  schedule:
#    - cron: 0 8 * * 5
  watch:
    types: [started]

env:
  OFP_LINK: https://down-cloud.rbinternationalnetwork.workers.dev//RMX2185_11_A.79_201104_e6e6c09b.ofp
  OFP_NAME: RMX2185_11_A.79_201104_e6e6c09b.ofp
  ZIP_NAME: RMX2185_11_A.79_201104_e6e6c09b.zip
  TZ: Asia/Kolkata

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: CleanUp Enviroment
         run: |
            wget https://raw.githubusercontent.com/Mediatek-leaks/script-personal/main/init.sh
            sudo bash init.sh
            
       - name: Downloading Ofp Now.. 
         run: |
            sudo apt-get install expect -y
            sudo -E apt-get -qq update
            wget $OFP_LINK
             
       - name: Decrypting Ozip Now
         run: |
             sudo -E apt-get -qq update
             sudo pip install docopt
             sudo pip install pycryptodome
             sudo apt-get install unzip
             unzip $ZIP_NAME -d out
             rm -rf $ZIP_NAME
             cd out
             wget https://raw.githubusercontent.com/bkerler/oppo_decrypt/master/ofp_mtk_decrypt.py
             sudo python3 ofp_mtk_decrypt.py $OFP_NAME out
             
       - name: Compress & Upload Decrypted Zip
         run: |
              zip -r9 Decrypted-ofp.zip out
              
       - name: Upload Decrypted Zip
         run: |
              expect -c " 
              spawn sftp ${{ secrets.SFUSER }}@frs.sourceforge.net
              expect \"yes/no\"
              send \"yes\r\"
              expect \"Password\"        
              send \"${{ secrets.SFPASS }}\r\"
              expect \"sftp> \"
              send \"cd ${{ secrets.SFDIR }}\r\"
              set timeout -1
              send \"put Decrypted-ofp.zip\r\"
              expect \"Uploading\"
              expect \"100%\"
              expect \"sftp>\"
              send \"bye\r\"
              interact"     
